// flow-typed signature: ba7efcf0ff0a93d8da2c96cc16c5ade8
// flow-typed version: <<STUB>>/testdouble_v3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testdouble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testdouble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testdouble/dist/testdouble' {
  declare module.exports: any;
}

declare module 'testdouble/lib/args-match' {
  declare module.exports: any;
}

declare module 'testdouble/lib/callback' {
  declare module.exports: any;
}

declare module 'testdouble/lib/config' {
  declare module.exports: any;
}

declare module 'testdouble/lib/constructor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/explain' {
  declare module.exports: any;
}

declare module 'testdouble/lib/function' {
  declare module.exports: any;
}

declare module 'testdouble/lib/function/create' {
  declare module.exports: any;
}

declare module 'testdouble/lib/function/generate-fake-function' {
  declare module.exports: any;
}

declare module 'testdouble/lib/function/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/create-imitation' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/initialize-names' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/is-generator' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/overwrite-children/chain-prototype' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/overwrite-children/copy-props' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/overwrite-children/gather-props' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/overwrite-children/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/overwrite-children/is-fakeable' {
  declare module.exports: any;
}

declare module 'testdouble/lib/imitate/overwrite-children/is-native-prototype' {
  declare module.exports: any;
}

declare module 'testdouble/lib/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/log' {
  declare module.exports: any;
}

declare module 'testdouble/lib/log/ensure-promise' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/anything' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/arg-that' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/captor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/contains' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/is-a' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/builtin/not' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/create' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/is-callback' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/is-matcher' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/notify-after-satisfaction' {
  declare module.exports: any;
}

declare module 'testdouble/lib/object' {
  declare module.exports: any;
}

declare module 'testdouble/lib/quibble.browser' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/is-constructor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/jest-module' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/module.browser' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/module' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/property' {
  declare module.exports: any;
}

declare module 'testdouble/lib/reset' {
  declare module.exports: any;
}

declare module 'testdouble/lib/satisfy/deliver-outcome' {
  declare module.exports: any;
}

declare module 'testdouble/lib/satisfy/find-last-stubbing-match' {
  declare module.exports: any;
}

declare module 'testdouble/lib/satisfy/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/satisfy/invoke-callbacks' {
  declare module.exports: any;
}

declare module 'testdouble/lib/share/call-later' {
  declare module.exports: any;
}

declare module 'testdouble/lib/share/create-promise' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/calls' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/stubbings' {
  declare module.exports: any;
}

declare module 'testdouble/lib/stringify/anything' {
  declare module.exports: any;
}

declare module 'testdouble/lib/stringify/arguments' {
  declare module.exports: any;
}

declare module 'testdouble/lib/value/call-log' {
  declare module.exports: any;
}

declare module 'testdouble/lib/value/call' {
  declare module.exports: any;
}

declare module 'testdouble/lib/value/double' {
  declare module.exports: any;
}

declare module 'testdouble/lib/value/stubbing-register' {
  declare module.exports: any;
}

declare module 'testdouble/lib/value/stubbing' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify/did-call-occur' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify/fail' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify/notify-satisfied-matchers' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify/pop-demonstration' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify/warn-if-also-stubbed' {
  declare module.exports: any;
}

declare module 'testdouble/lib/version' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when/add-implied-callback-arg-if-necessary' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when/chain-stubbing' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when/ensure-rehearsal' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/wrap/lodash' {
  declare module.exports: any;
}

declare module 'testdouble/src/args-match' {
  declare module.exports: any;
}

declare module 'testdouble/src/callback' {
  declare module.exports: any;
}

declare module 'testdouble/src/config' {
  declare module.exports: any;
}

declare module 'testdouble/src/constructor' {
  declare module.exports: any;
}

declare module 'testdouble/src/explain' {
  declare module.exports: any;
}

declare module 'testdouble/src/function' {
  declare module.exports: any;
}

declare module 'testdouble/src/function/create' {
  declare module.exports: any;
}

declare module 'testdouble/src/function/generate-fake-function' {
  declare module.exports: any;
}

declare module 'testdouble/src/function/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/create-imitation' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/initialize-names' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/is-generator' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/overwrite-children/chain-prototype' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/overwrite-children/copy-props' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/overwrite-children/gather-props' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/overwrite-children/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/overwrite-children/is-fakeable' {
  declare module.exports: any;
}

declare module 'testdouble/src/imitate/overwrite-children/is-native-prototype' {
  declare module.exports: any;
}

declare module 'testdouble/src/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/log' {
  declare module.exports: any;
}

declare module 'testdouble/src/log/ensure-promise' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/anything' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/arg-that' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/captor' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/contains' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/is-a' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/builtin/not' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/create' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/is-callback' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/is-matcher' {
  declare module.exports: any;
}

declare module 'testdouble/src/matchers/notify-after-satisfaction' {
  declare module.exports: any;
}

declare module 'testdouble/src/object' {
  declare module.exports: any;
}

declare module 'testdouble/src/quibble.browser' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/is-constructor' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/jest-module' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/module.browser' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/module' {
  declare module.exports: any;
}

declare module 'testdouble/src/replace/property' {
  declare module.exports: any;
}

declare module 'testdouble/src/reset' {
  declare module.exports: any;
}

declare module 'testdouble/src/satisfy/deliver-outcome' {
  declare module.exports: any;
}

declare module 'testdouble/src/satisfy/find-last-stubbing-match' {
  declare module.exports: any;
}

declare module 'testdouble/src/satisfy/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/satisfy/invoke-callbacks' {
  declare module.exports: any;
}

declare module 'testdouble/src/share/call-later' {
  declare module.exports: any;
}

declare module 'testdouble/src/share/create-promise' {
  declare module.exports: any;
}

declare module 'testdouble/src/store/calls' {
  declare module.exports: any;
}

declare module 'testdouble/src/store/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/store/stubbings' {
  declare module.exports: any;
}

declare module 'testdouble/src/stringify/anything' {
  declare module.exports: any;
}

declare module 'testdouble/src/stringify/arguments' {
  declare module.exports: any;
}

declare module 'testdouble/src/value/call-log' {
  declare module.exports: any;
}

declare module 'testdouble/src/value/call' {
  declare module.exports: any;
}

declare module 'testdouble/src/value/double' {
  declare module.exports: any;
}

declare module 'testdouble/src/value/stubbing-register' {
  declare module.exports: any;
}

declare module 'testdouble/src/value/stubbing' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify/did-call-occur' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify/fail' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify/notify-satisfied-matchers' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify/pop-demonstration' {
  declare module.exports: any;
}

declare module 'testdouble/src/verify/warn-if-also-stubbed' {
  declare module.exports: any;
}

declare module 'testdouble/src/version' {
  declare module.exports: any;
}

declare module 'testdouble/src/when' {
  declare module.exports: any;
}

declare module 'testdouble/src/when/add-implied-callback-arg-if-necessary' {
  declare module.exports: any;
}

declare module 'testdouble/src/when/chain-stubbing' {
  declare module.exports: any;
}

declare module 'testdouble/src/when/ensure-rehearsal' {
  declare module.exports: any;
}

declare module 'testdouble/src/when/index' {
  declare module.exports: any;
}

declare module 'testdouble/src/wrap/lodash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testdouble/dist/testdouble.js' {
  declare module.exports: $Exports<'testdouble/dist/testdouble'>;
}
declare module 'testdouble/lib/args-match.js' {
  declare module.exports: $Exports<'testdouble/lib/args-match'>;
}
declare module 'testdouble/lib/callback.js' {
  declare module.exports: $Exports<'testdouble/lib/callback'>;
}
declare module 'testdouble/lib/config.js' {
  declare module.exports: $Exports<'testdouble/lib/config'>;
}
declare module 'testdouble/lib/constructor.js' {
  declare module.exports: $Exports<'testdouble/lib/constructor'>;
}
declare module 'testdouble/lib/explain.js' {
  declare module.exports: $Exports<'testdouble/lib/explain'>;
}
declare module 'testdouble/lib/function.js' {
  declare module.exports: $Exports<'testdouble/lib/function'>;
}
declare module 'testdouble/lib/function/create.js' {
  declare module.exports: $Exports<'testdouble/lib/function/create'>;
}
declare module 'testdouble/lib/function/generate-fake-function.js' {
  declare module.exports: $Exports<'testdouble/lib/function/generate-fake-function'>;
}
declare module 'testdouble/lib/function/index.js' {
  declare module.exports: $Exports<'testdouble/lib/function/index'>;
}
declare module 'testdouble/lib/imitate/create-imitation.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/create-imitation'>;
}
declare module 'testdouble/lib/imitate/index.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/index'>;
}
declare module 'testdouble/lib/imitate/initialize-names.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/initialize-names'>;
}
declare module 'testdouble/lib/imitate/is-generator.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/is-generator'>;
}
declare module 'testdouble/lib/imitate/overwrite-children/chain-prototype.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/overwrite-children/chain-prototype'>;
}
declare module 'testdouble/lib/imitate/overwrite-children/copy-props.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/overwrite-children/copy-props'>;
}
declare module 'testdouble/lib/imitate/overwrite-children/gather-props.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/overwrite-children/gather-props'>;
}
declare module 'testdouble/lib/imitate/overwrite-children/index.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/overwrite-children/index'>;
}
declare module 'testdouble/lib/imitate/overwrite-children/is-fakeable.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/overwrite-children/is-fakeable'>;
}
declare module 'testdouble/lib/imitate/overwrite-children/is-native-prototype.js' {
  declare module.exports: $Exports<'testdouble/lib/imitate/overwrite-children/is-native-prototype'>;
}
declare module 'testdouble/lib/index.js' {
  declare module.exports: $Exports<'testdouble/lib/index'>;
}
declare module 'testdouble/lib/log.js' {
  declare module.exports: $Exports<'testdouble/lib/log'>;
}
declare module 'testdouble/lib/log/ensure-promise.js' {
  declare module.exports: $Exports<'testdouble/lib/log/ensure-promise'>;
}
declare module 'testdouble/lib/matchers/builtin/anything.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/anything'>;
}
declare module 'testdouble/lib/matchers/builtin/arg-that.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/arg-that'>;
}
declare module 'testdouble/lib/matchers/builtin/captor.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/captor'>;
}
declare module 'testdouble/lib/matchers/builtin/contains.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/contains'>;
}
declare module 'testdouble/lib/matchers/builtin/is-a.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/is-a'>;
}
declare module 'testdouble/lib/matchers/builtin/not.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/builtin/not'>;
}
declare module 'testdouble/lib/matchers/create.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/create'>;
}
declare module 'testdouble/lib/matchers/index.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/index'>;
}
declare module 'testdouble/lib/matchers/is-callback.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/is-callback'>;
}
declare module 'testdouble/lib/matchers/is-matcher.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/is-matcher'>;
}
declare module 'testdouble/lib/matchers/notify-after-satisfaction.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/notify-after-satisfaction'>;
}
declare module 'testdouble/lib/object.js' {
  declare module.exports: $Exports<'testdouble/lib/object'>;
}
declare module 'testdouble/lib/quibble.browser.js' {
  declare module.exports: $Exports<'testdouble/lib/quibble.browser'>;
}
declare module 'testdouble/lib/replace/index.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/index'>;
}
declare module 'testdouble/lib/replace/is-constructor.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/is-constructor'>;
}
declare module 'testdouble/lib/replace/jest-module.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/jest-module'>;
}
declare module 'testdouble/lib/replace/module.browser.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/module.browser'>;
}
declare module 'testdouble/lib/replace/module.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/module'>;
}
declare module 'testdouble/lib/replace/property.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/property'>;
}
declare module 'testdouble/lib/reset.js' {
  declare module.exports: $Exports<'testdouble/lib/reset'>;
}
declare module 'testdouble/lib/satisfy/deliver-outcome.js' {
  declare module.exports: $Exports<'testdouble/lib/satisfy/deliver-outcome'>;
}
declare module 'testdouble/lib/satisfy/find-last-stubbing-match.js' {
  declare module.exports: $Exports<'testdouble/lib/satisfy/find-last-stubbing-match'>;
}
declare module 'testdouble/lib/satisfy/index.js' {
  declare module.exports: $Exports<'testdouble/lib/satisfy/index'>;
}
declare module 'testdouble/lib/satisfy/invoke-callbacks.js' {
  declare module.exports: $Exports<'testdouble/lib/satisfy/invoke-callbacks'>;
}
declare module 'testdouble/lib/share/call-later.js' {
  declare module.exports: $Exports<'testdouble/lib/share/call-later'>;
}
declare module 'testdouble/lib/share/create-promise.js' {
  declare module.exports: $Exports<'testdouble/lib/share/create-promise'>;
}
declare module 'testdouble/lib/store/calls.js' {
  declare module.exports: $Exports<'testdouble/lib/store/calls'>;
}
declare module 'testdouble/lib/store/index.js' {
  declare module.exports: $Exports<'testdouble/lib/store/index'>;
}
declare module 'testdouble/lib/store/stubbings.js' {
  declare module.exports: $Exports<'testdouble/lib/store/stubbings'>;
}
declare module 'testdouble/lib/stringify/anything.js' {
  declare module.exports: $Exports<'testdouble/lib/stringify/anything'>;
}
declare module 'testdouble/lib/stringify/arguments.js' {
  declare module.exports: $Exports<'testdouble/lib/stringify/arguments'>;
}
declare module 'testdouble/lib/value/call-log.js' {
  declare module.exports: $Exports<'testdouble/lib/value/call-log'>;
}
declare module 'testdouble/lib/value/call.js' {
  declare module.exports: $Exports<'testdouble/lib/value/call'>;
}
declare module 'testdouble/lib/value/double.js' {
  declare module.exports: $Exports<'testdouble/lib/value/double'>;
}
declare module 'testdouble/lib/value/stubbing-register.js' {
  declare module.exports: $Exports<'testdouble/lib/value/stubbing-register'>;
}
declare module 'testdouble/lib/value/stubbing.js' {
  declare module.exports: $Exports<'testdouble/lib/value/stubbing'>;
}
declare module 'testdouble/lib/verify.js' {
  declare module.exports: $Exports<'testdouble/lib/verify'>;
}
declare module 'testdouble/lib/verify/did-call-occur.js' {
  declare module.exports: $Exports<'testdouble/lib/verify/did-call-occur'>;
}
declare module 'testdouble/lib/verify/fail.js' {
  declare module.exports: $Exports<'testdouble/lib/verify/fail'>;
}
declare module 'testdouble/lib/verify/index.js' {
  declare module.exports: $Exports<'testdouble/lib/verify/index'>;
}
declare module 'testdouble/lib/verify/notify-satisfied-matchers.js' {
  declare module.exports: $Exports<'testdouble/lib/verify/notify-satisfied-matchers'>;
}
declare module 'testdouble/lib/verify/pop-demonstration.js' {
  declare module.exports: $Exports<'testdouble/lib/verify/pop-demonstration'>;
}
declare module 'testdouble/lib/verify/warn-if-also-stubbed.js' {
  declare module.exports: $Exports<'testdouble/lib/verify/warn-if-also-stubbed'>;
}
declare module 'testdouble/lib/version.js' {
  declare module.exports: $Exports<'testdouble/lib/version'>;
}
declare module 'testdouble/lib/when.js' {
  declare module.exports: $Exports<'testdouble/lib/when'>;
}
declare module 'testdouble/lib/when/add-implied-callback-arg-if-necessary.js' {
  declare module.exports: $Exports<'testdouble/lib/when/add-implied-callback-arg-if-necessary'>;
}
declare module 'testdouble/lib/when/chain-stubbing.js' {
  declare module.exports: $Exports<'testdouble/lib/when/chain-stubbing'>;
}
declare module 'testdouble/lib/when/ensure-rehearsal.js' {
  declare module.exports: $Exports<'testdouble/lib/when/ensure-rehearsal'>;
}
declare module 'testdouble/lib/when/index.js' {
  declare module.exports: $Exports<'testdouble/lib/when/index'>;
}
declare module 'testdouble/lib/wrap/lodash.js' {
  declare module.exports: $Exports<'testdouble/lib/wrap/lodash'>;
}
declare module 'testdouble/src/args-match.js' {
  declare module.exports: $Exports<'testdouble/src/args-match'>;
}
declare module 'testdouble/src/callback.js' {
  declare module.exports: $Exports<'testdouble/src/callback'>;
}
declare module 'testdouble/src/config.js' {
  declare module.exports: $Exports<'testdouble/src/config'>;
}
declare module 'testdouble/src/constructor.js' {
  declare module.exports: $Exports<'testdouble/src/constructor'>;
}
declare module 'testdouble/src/explain.js' {
  declare module.exports: $Exports<'testdouble/src/explain'>;
}
declare module 'testdouble/src/function.js' {
  declare module.exports: $Exports<'testdouble/src/function'>;
}
declare module 'testdouble/src/function/create.js' {
  declare module.exports: $Exports<'testdouble/src/function/create'>;
}
declare module 'testdouble/src/function/generate-fake-function.js' {
  declare module.exports: $Exports<'testdouble/src/function/generate-fake-function'>;
}
declare module 'testdouble/src/function/index.js' {
  declare module.exports: $Exports<'testdouble/src/function/index'>;
}
declare module 'testdouble/src/imitate/create-imitation.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/create-imitation'>;
}
declare module 'testdouble/src/imitate/index.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/index'>;
}
declare module 'testdouble/src/imitate/initialize-names.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/initialize-names'>;
}
declare module 'testdouble/src/imitate/is-generator.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/is-generator'>;
}
declare module 'testdouble/src/imitate/overwrite-children/chain-prototype.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/overwrite-children/chain-prototype'>;
}
declare module 'testdouble/src/imitate/overwrite-children/copy-props.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/overwrite-children/copy-props'>;
}
declare module 'testdouble/src/imitate/overwrite-children/gather-props.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/overwrite-children/gather-props'>;
}
declare module 'testdouble/src/imitate/overwrite-children/index.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/overwrite-children/index'>;
}
declare module 'testdouble/src/imitate/overwrite-children/is-fakeable.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/overwrite-children/is-fakeable'>;
}
declare module 'testdouble/src/imitate/overwrite-children/is-native-prototype.js' {
  declare module.exports: $Exports<'testdouble/src/imitate/overwrite-children/is-native-prototype'>;
}
declare module 'testdouble/src/index.js' {
  declare module.exports: $Exports<'testdouble/src/index'>;
}
declare module 'testdouble/src/log.js' {
  declare module.exports: $Exports<'testdouble/src/log'>;
}
declare module 'testdouble/src/log/ensure-promise.js' {
  declare module.exports: $Exports<'testdouble/src/log/ensure-promise'>;
}
declare module 'testdouble/src/matchers/builtin/anything.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/anything'>;
}
declare module 'testdouble/src/matchers/builtin/arg-that.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/arg-that'>;
}
declare module 'testdouble/src/matchers/builtin/captor.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/captor'>;
}
declare module 'testdouble/src/matchers/builtin/contains.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/contains'>;
}
declare module 'testdouble/src/matchers/builtin/is-a.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/is-a'>;
}
declare module 'testdouble/src/matchers/builtin/not.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/builtin/not'>;
}
declare module 'testdouble/src/matchers/create.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/create'>;
}
declare module 'testdouble/src/matchers/index.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/index'>;
}
declare module 'testdouble/src/matchers/is-callback.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/is-callback'>;
}
declare module 'testdouble/src/matchers/is-matcher.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/is-matcher'>;
}
declare module 'testdouble/src/matchers/notify-after-satisfaction.js' {
  declare module.exports: $Exports<'testdouble/src/matchers/notify-after-satisfaction'>;
}
declare module 'testdouble/src/object.js' {
  declare module.exports: $Exports<'testdouble/src/object'>;
}
declare module 'testdouble/src/quibble.browser.js' {
  declare module.exports: $Exports<'testdouble/src/quibble.browser'>;
}
declare module 'testdouble/src/replace/index.js' {
  declare module.exports: $Exports<'testdouble/src/replace/index'>;
}
declare module 'testdouble/src/replace/is-constructor.js' {
  declare module.exports: $Exports<'testdouble/src/replace/is-constructor'>;
}
declare module 'testdouble/src/replace/jest-module.js' {
  declare module.exports: $Exports<'testdouble/src/replace/jest-module'>;
}
declare module 'testdouble/src/replace/module.browser.js' {
  declare module.exports: $Exports<'testdouble/src/replace/module.browser'>;
}
declare module 'testdouble/src/replace/module.js' {
  declare module.exports: $Exports<'testdouble/src/replace/module'>;
}
declare module 'testdouble/src/replace/property.js' {
  declare module.exports: $Exports<'testdouble/src/replace/property'>;
}
declare module 'testdouble/src/reset.js' {
  declare module.exports: $Exports<'testdouble/src/reset'>;
}
declare module 'testdouble/src/satisfy/deliver-outcome.js' {
  declare module.exports: $Exports<'testdouble/src/satisfy/deliver-outcome'>;
}
declare module 'testdouble/src/satisfy/find-last-stubbing-match.js' {
  declare module.exports: $Exports<'testdouble/src/satisfy/find-last-stubbing-match'>;
}
declare module 'testdouble/src/satisfy/index.js' {
  declare module.exports: $Exports<'testdouble/src/satisfy/index'>;
}
declare module 'testdouble/src/satisfy/invoke-callbacks.js' {
  declare module.exports: $Exports<'testdouble/src/satisfy/invoke-callbacks'>;
}
declare module 'testdouble/src/share/call-later.js' {
  declare module.exports: $Exports<'testdouble/src/share/call-later'>;
}
declare module 'testdouble/src/share/create-promise.js' {
  declare module.exports: $Exports<'testdouble/src/share/create-promise'>;
}
declare module 'testdouble/src/store/calls.js' {
  declare module.exports: $Exports<'testdouble/src/store/calls'>;
}
declare module 'testdouble/src/store/index.js' {
  declare module.exports: $Exports<'testdouble/src/store/index'>;
}
declare module 'testdouble/src/store/stubbings.js' {
  declare module.exports: $Exports<'testdouble/src/store/stubbings'>;
}
declare module 'testdouble/src/stringify/anything.js' {
  declare module.exports: $Exports<'testdouble/src/stringify/anything'>;
}
declare module 'testdouble/src/stringify/arguments.js' {
  declare module.exports: $Exports<'testdouble/src/stringify/arguments'>;
}
declare module 'testdouble/src/value/call-log.js' {
  declare module.exports: $Exports<'testdouble/src/value/call-log'>;
}
declare module 'testdouble/src/value/call.js' {
  declare module.exports: $Exports<'testdouble/src/value/call'>;
}
declare module 'testdouble/src/value/double.js' {
  declare module.exports: $Exports<'testdouble/src/value/double'>;
}
declare module 'testdouble/src/value/stubbing-register.js' {
  declare module.exports: $Exports<'testdouble/src/value/stubbing-register'>;
}
declare module 'testdouble/src/value/stubbing.js' {
  declare module.exports: $Exports<'testdouble/src/value/stubbing'>;
}
declare module 'testdouble/src/verify.js' {
  declare module.exports: $Exports<'testdouble/src/verify'>;
}
declare module 'testdouble/src/verify/did-call-occur.js' {
  declare module.exports: $Exports<'testdouble/src/verify/did-call-occur'>;
}
declare module 'testdouble/src/verify/fail.js' {
  declare module.exports: $Exports<'testdouble/src/verify/fail'>;
}
declare module 'testdouble/src/verify/index.js' {
  declare module.exports: $Exports<'testdouble/src/verify/index'>;
}
declare module 'testdouble/src/verify/notify-satisfied-matchers.js' {
  declare module.exports: $Exports<'testdouble/src/verify/notify-satisfied-matchers'>;
}
declare module 'testdouble/src/verify/pop-demonstration.js' {
  declare module.exports: $Exports<'testdouble/src/verify/pop-demonstration'>;
}
declare module 'testdouble/src/verify/warn-if-also-stubbed.js' {
  declare module.exports: $Exports<'testdouble/src/verify/warn-if-also-stubbed'>;
}
declare module 'testdouble/src/version.js' {
  declare module.exports: $Exports<'testdouble/src/version'>;
}
declare module 'testdouble/src/when.js' {
  declare module.exports: $Exports<'testdouble/src/when'>;
}
declare module 'testdouble/src/when/add-implied-callback-arg-if-necessary.js' {
  declare module.exports: $Exports<'testdouble/src/when/add-implied-callback-arg-if-necessary'>;
}
declare module 'testdouble/src/when/chain-stubbing.js' {
  declare module.exports: $Exports<'testdouble/src/when/chain-stubbing'>;
}
declare module 'testdouble/src/when/ensure-rehearsal.js' {
  declare module.exports: $Exports<'testdouble/src/when/ensure-rehearsal'>;
}
declare module 'testdouble/src/when/index.js' {
  declare module.exports: $Exports<'testdouble/src/when/index'>;
}
declare module 'testdouble/src/wrap/lodash.js' {
  declare module.exports: $Exports<'testdouble/src/wrap/lodash'>;
}
